### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by sweethoneycode** [onepagezen/ob-frontend#14]
I was running gatsby build and saw this error in the terminal. Now sure what it means.

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value: Date.
    at SchemaComposer.createTempTC (C:\Users\jonah\Code\blog\node_modules\graphql-compose\lib\SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer (C:\Users\jonah\Code\blog\node_modules\graphql-compose\lib\SchemaComposer.js:563:27)
    at createSchemaComposer (C:\Users\jonah\Code\blog\node_modules\gatsby\src\schema\schema-composer.js:16:18)
    at build (C:\Users\jonah\Code\blog\node_modules\gatsby\src\schema\index.js:104:26)
    at buildSchema (C:\Users\jonah\Code\blog\node_modules\gatsby\src\services\build-schema.ts:19:3)'

**Comment by petejos80** [comment]
Were you able to get the issue resolved?  If not, try the following (from top to bottom):

https://github.com/gatsbyjs/gatsby/issues/13278#issuecomment-630751552
https://github.com/gatsbyjs/gatsby/issues/13278#issuecomment-620360475

Let me know if you need additional help.  Thanks for submitting the issue!

**Comment by SergioMaurySterling** [comment]
Im still facing this issue
